language: c

env:
  - LUA='Lua 5.1'
  - LUA='Lua 5.2'
  - LUA='LuaJIT 2.0'

before_install:
  - bash .travis_setup.sh

install:
  - sudo luarocks make --server=http://rocks.moonscript.org
  - sudo apt-get update -qq
  - sudo apt-get install -qq libev-dev
  - sudo luarocks install lua-ev scm --server=http://luarocks.org/repositories/rocks-scm/
  - sudo luarocks install copas
  - sudo luarocks install moonscript

script: ./bin/busted.lua spec

branches:
  except:
    - gh-pages
